services:
  xmcloud-vercel-integration:
      image: xmcloud-vercel-integration:latest
      build:
        context: .
        dockerfile: ./docker/build/xmcloud-vercel-int/Dockerfile
        args:
          BASE_IMAGE: mcr.microsoft.com/dotnet/sdk:6.0-nanoserver-1809
          NODEJS_VERSION: 14.15.3
      environment:
        HOST: ${HOST}
        PWSH_LOG_FOLDER: ${PWSH_LOG_FOLDER}
        GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
        GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
        GITHUB_CLONE_FOLDER: ${GITHUB_CLONE_FOLDER}
        GITHUB_CLONE_REDIRECT_URL: ${GITHUB_CLONE_REDIRECT_URL}
        VERCEL_CLIENT_ID: ${VERCEL_CLIENT_ID}
        VERCEL_CLIENT_SECRET: ${VERCEL_CLIENT_SECRET}
        XM_CLOUD_DEPLOY_API_URL: ${XM_CLOUD_DEPLOY_API_URL}
      volumes:
      - .:C:\app
      ports:
      - "3000:3000"