module.exports = {
  //add other configs here too
  env: {
    GITHUB_CLIENT_ID: process.env.GITHUB_CLIENT_ID,
    GITHUB_CLONE_REDIRECT_URL: process.env.GITHUB_CLONE_REDIRECT_URL,
    GIT_CLONE_REDIRECT_URL: process.env.GIT_CLONE_REPO_API_URL,
    GITHUB_AUTHORIZE_URL: process.env.GITHUB_AUTHORIZE_URL,
    VERCEL_GET_TOKEN_URL: process.env.VERCEL_GET_TOKEN_URL,
    VERCEL_GET_PROJECT_ID_URL: process.env.VERCEL_GET_PROJECT_ID_URL,
    VERCEL_CLIENT_ID: process.env.VERCEL_CLIENT_ID,
    VERCEL_CLIENT_SECRET: process.env.VERCEL_CLIENT_SECRET,
    VERCEL_REDIRECT_HOST: process.env.HOST,
    NEXT_PUBLIC_KEY: process.env.NEXT_PUBLIC_KEY,
    XM_CLOUD_LOGIN_API_URL: process.env.XM_CLOUD_LOGIN_API_URL,
    XM_CLOUD_FETCH_PROJECT_API_URL: process.env.XM_CLOUD_FETCH_PROJECT_API_URL,
  },
};
